export const ENRICHMENT_FIELD_FILLING_CONTRACT = {
  value_style: {
    field_names: "Use the schema field names exactly.",
    enum_values: "Use exact lowercase enum values from the schema.",
    categorical_arrays: "Use stable snake_case slugs only. Do not use Title Case, prose phrases, or mixed casing.",
    categorical_array_breadth: "Include every source-supported array value up to the schema cap. Do not collapse sectors, stages, geographies, asset classes, routes, or capabilities to one representative item.",
    unknown_arrays: "If an array value is unknown, use [] instead of adding 'unknown' as an array item.",
    unknown_strings: "Use the exact string 'unknown' only for scalar string fields where the schema requires a string.",
    unknown_numbers: "Use null for unknown numeric fields such as AUM or optional size fields.",
  },
  type_values: {
    single_family_office: "One family's own family office or investment office.",
    multi_family_office: "A platform serving multiple families as a family office or outsourced CIO.",
    private_investment_office: "Private investment office for family or UHNW capital where single-vs-multi is unclear.",
    family_investment_vehicle: "A named investing vehicle or evergreen capital arm inside a family office.",
    family_holding_company: "Family-controlled holding company with investment activity.",
    fund_of_funds: "Fund-of-funds or multi-manager vehicle allocating to external funds.",
    pension_fund: "Public, corporate, union, or private pension allocator.",
    endowment: "University, school, hospital, museum, or other institutional endowment.",
    foundation: "Private, charitable, community, or corporate foundation with allocatable capital.",
    sovereign_wealth_fund: "Government-owned sovereign wealth or national investment fund.",
    insurance_company: "Insurance balance-sheet allocator.",
    bank: "Bank or bank-owned investment platform.",
    private_bank: "Private bank or private-wealth platform allocating client capital.",
    asset_manager: "Asset manager or investment manager.",
    wealth_manager: "Wealth-management platform serving HNW/UHNW clients.",
    ria: "Registered investment advisor or independent wealth advisor.",
    outsourced_cio: "OCIO or discretionary institutional/family allocator.",
    fund_manager: "Fund manager that may be a partner, competitor, or non-LP target.",
    corporate_investor: "Corporate venture, corporate development, or corporate investment arm.",
    strategic_investor: "Strategic operating-company investor.",
    government_allocator: "Government, municipal, public-sector, or agency allocator.",
    development_finance_institution: "DFI or development-backed investment institution.",
    angel_network: "Angel group, syndicate, or organized individual-investor network.",
    hnwi_investor: "Individual HNWI/UHNW investor where no institution is clear.",
    placement_agent: "Placement agent or capital-raising intermediary.",
    consultant_gatekeeper: "Investment consultant, advisor, or gatekeeper to allocators.",
    not_lp_target: "False positive or entity unlikely to invest in VC funds.",
    unknown: "Only when public evidence cannot support a more specific type.",
  },
  yes_no_unknown_fields: [
    "capital_profile.invests_in_vc_funds",
    "capital_profile.invests_directly",
    "capital_profile.co_investment_appetite",
    "capital_profile.fund_commitment_appetite",
    "capital_profile.emerging_manager_appetite",
    "capital_profile.first_time_fund_appetite",
  ],
  vc_fundraise_field_priority: {
    must_have: {
      type: "Required filter. Classify the capital source using the LP/institution/entity type enum with public evidence.",
      detailed_profile_summary: "Required profile field. Summarize what the entity is, where it is based, who/what capital it represents, and the evidence-backed investment/allocator posture.",
      geography_focus: "Required filter. Capture operating or investment geography using stable snake_case slugs.",
      sector_focus: "Required filter. Capture sectors/themes useful for VC fundraise targeting.",
      stage_focus: "Required filter. Capture investment stage focus when public evidence or the source record supports it.",
      capital_source_role: "Required filter. Distinguish principal capital from advisor/OCIO/client allocator/gatekeeper models.",
      fund_allocation_signal: "Required filter. Classify what the evidence really proves about fund allocation, without collapsing manager selection into VC LP appetite.",
      vc_fund_lp_signal: "Required filter. Use explicit_yes only when a source explicitly says venture/VC fund LP or venture fund investments.",
      fund_asset_classes: "Required filter. Capture asset classes such as venture_capital, growth_equity, buyout_private_equity, private_credit, real_estate, hedge_funds, private_markets.",
      investment_routes: "Required filter. Capture routes such as direct_investments, fund_commitments, co_investments, external_managers, fund_of_funds, secondaries.",
      allocator_capabilities: "Required when present. Capture manager_selection, due_diligence, asset_allocation, investment_monitoring, ocio, private_investment_screening.",
      evidence_strength: "Required quality filter. Classify the strongest evidence supporting capital-allocation fields.",
      fundraise_fit_notes: "Required fit assessment. Explain why a VC fund should or should not prioritize this capital source, using evidence-backed facts only.",
    },
    optional_if_available: {
      logo_url: "Capture a clean public logo URL when easy to obtain from the official website or source record; otherwise use unknown.",
      favicon_url: "Capture a clean favicon URL when easy to obtain from the official website or source record; otherwise use unknown.",
      address: "Capture a public office/headquarters address only when directly stated by a source.",
      postal_code: "Capture the postal/ZIP code only when directly stated or directly extractable from the sourced address.",
      invests_in_vc_funds: "Backward-compatible field only. Fill yes only when vc_fund_lp_signal is explicit_yes; otherwise use unknown/no even when fund_allocation_signal shows private-market or manager-selection evidence.",
      fund_commitment_appetite: "Backward-compatible field only. Fill yes when fund_allocation_signal is explicit_vc_fund_lp, explicit_private_market_fund_lp, external_manager_allocator, or fund_of_funds_platform.",
      invests_directly: "Supporting signal, not a product-readiness blocker for a VC fundraise. Fill yes only with explicit direct-company investment evidence. Unknown is acceptable.",
      co_investment_appetite: "Supporting signal for SPVs/co-investments, not a blocker for normal fund LP fundraising. Fill yes only with explicit co-invest/club-deal/alongside-investor language. Unknown is acceptable.",
      cheque_size: "Nice-to-have only. Populate cheque/commitment size fields only when the source explicitly states them.",
      best_contact: "Nice-to-have only. Capture a public contact only when the source directly names a relevant person; otherwise omit or use unknown values.",
    },
  },
  categorical_array_examples: {
    sector_focus: ["technology", "fintech", "healthcare", "real_estate", "private_equity", "private_credit", "venture_capital"],
    stage_focus: ["pre_seed", "seed", "series_a", "early_stage", "growth_stage", "late_stage", "buyout", "middle_market"],
    fund_asset_classes: ["venture_capital", "growth_equity", "buyout_private_equity", "private_credit", "real_estate", "real_assets", "hedge_funds", "private_markets"],
    investment_routes: ["direct_investments", "fund_commitments", "co_investments", "external_managers", "fund_of_funds", "secondaries", "real_estate_projects", "public_markets"],
    allocator_capabilities: ["manager_selection", "asset_allocation", "due_diligence", "investment_monitoring", "ocio", "private_investment_screening", "consolidated_reporting"],
    geography_focus: ["united_states", "north_america", "europe", "asia_pacific", "global", "united_kingdom"],
    fund_geography_preference: ["united_states", "north_america", "europe", "asia_pacific", "global", "emerging_markets"],
    direct_geography_preference: ["united_states", "north_america", "europe", "asia_pacific", "global", "emerging_markets"],
    business_model_preferences: ["b2b", "b2c", "saas", "direct_investment", "co_investment", "fund_investment", "control_investments"],
    impact_or_values_themes: ["sustainability", "social_impact", "esg", "innovation", "wealth_preservation", "philanthropy"],
    exclusion_tags: ["weapons", "tobacco", "gambling"],
  },
  sensitive_field_rules: [
    "Do not fill AUM, net worth, commitment size, cheque size, fund size preference, emerging manager appetite, first-time fund appetite, or exclusions unless directly stated by a source. These are optional; unknown is fine. Do not output email fields or decision-maker email addresses.",
    "Do not infer VC fund investment appetite from direct startup investing, generic funds language, external managers, manager selection, private equity funds, or OCIO language.",
    "Do not infer no VC fund investment appetite from generic wealth-management, advisory, client-service, fee-only, or outsourced-CIO wording.",
    "Do not infer direct/co-invest appetite from generic institution, private-markets, allocator, or wealth-management wording.",
    "Do not copy a direct-investment cheque size into fund_cheque_size_* fields; direct deal checks and LP/fund commitment checks are different.",
    "Do not infer institution type or LP status from the bought list label or portfolio examples.",
  ],
  evidence_rules: [
    "Every material populated field needs a source_evidence item whose field_path exactly matches that field or a parent path.",
    "Use clean URLs only. No markdown citations and no tracking parameters.",
    "Use official_website only for URLs on the entity's own domain.",
    "Use source_record only for bought-list context, never as sole proof of institution type or LP status.",
    "If a value is not evidence-backed, leave it unknown, null, [], or blank rather than guessing.",
    "Use evidence_strength=third_party_explicit when a credible public third-party profile directly supports the allocator or fund activity claim.",
  ],
  fit_assessment_rules: [
    "fundraise_fit_notes and fit_risk_notes must be specific, conservative, and sourced.",
    "These fields are fit assessment, not outreach copy. Do not write recommended asks, message snippets, subject lines, or personalized copy.",
    "If there is no evidence-backed fit assessment, use 'unknown' for fundraise_fit_notes and fit_risk_notes.",
    "warm_intro_paths should contain only public, evidence-backed names/organizations or [].",
  ],
  portfolio_rules: [
    "known_fund_investments must be fund commitments, manager relationships, or named funds only.",
    "known_direct_investments must be direct company/startup investments.",
    "Do not put portfolio companies or funding rounds in known_fund_investments.",
    "Do not use placeholders, category labels, numbered generic names, or inferred examples such as financial_services_firm_1, company_2, portfolio_company, fund_1, or real_estate_platform. Leave arrays empty unless a source names the actual organization.",
  ],
} as const;
